### ISSUE TITLE
bpf fails to build with clang-22 due to `incompatible pointer type` error

### ISSUE THREAD

**Issue by NHOrus** [facebookincubator/below#8275]
Error, build with Clang-22.1.0:
```
error: failed to run custom build command for `below v0.11.0 (/var/tmp/portage/sys-process/below-0.11.0-r1/work/below-0.11.0/below)`

Caused by:
  process didn't exit successfully: `/var/tmp/portage/sys-process/below-0.11.0-r1/work/below-0.11.0/target/release/build/below-2d797d197c68f8c5/build-script-build` (exit status: 101)
  --- stderr

  thread 'main' (4664) panicked at below/build.rs:32:37:
  called `Result::unwrap()` on an `Err` value: failed to build `./src/bpf/exitstat.bpf.c`

  Caused by:
      0: failed to compile `./src/bpf/exitstat.bpf.c`
      1: failed to compile /var/tmp/portage/sys-process/below-0.11.0-r1/temp/.tmpZqxH6H/exitstat.bpf.c from ./src/bpf/exitstat.bpf.c
      2: command `clang -I /var/tmp/portage/sys-process/below-0.11.0-r1/temp/.tmpMQP6UP/bpf/src -fno-stack-protector -D__TARGET_ARCH_x86 -g -O2 -target bpf -c ./src/bpf/exitstat.bpf.c -o /var/tmp/portage/sys-process/below-0.11.0-r1/temp/.tmpZqxH6H/exitstat.bpf.c` failed (exit status: 1)
      3: ./src/bpf/exitstat.bpf.c:140:39: error: incompatible pointer types initializing 'const struct mm_struct___pre62 *' with an expression of type 'const struct mm_struct *' [-Wincompatible-pointer-types]
           140 |       const struct mm_struct___pre62 *mms = mm;
               |                                       ^     ~~
```
Gentoo bug: https://bugs.gentoo.org/970763

**Comment by dottorblaster** [comment]
Just submitted #8280 to fix the issue.

Also, applied this to [our openSUSE package](https://build.opensuse.org/projects/utilities/packages/below/files/002-llvm22-explicit-casts.patch).
